# Generated by Django 5.2.8 on 2025-11-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='productos.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', to='productos.producto'),
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.cliente')),
            ],
        ),
    ]
