# Generated by Django 5.2.8 on 2025-11-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilCliente',
        ),
    ]
